aws_snowflake_dbt_project:
  outputs:
    dev:
      account: WQMDHIT-UN15360
      database: AIRBNB
      password: Khan@123456789
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: saidrasool402
      warehouse: Compute_WH
  target: dev
